import { z } from 'zod';
import { AudioSchema } from './map.js';

/** Minimal System.json schema for the fields we need. Use passthrough for unknown fields. */
export const SystemSchema = z.object({
  airship: z.unknown(),
  armorTypes: z.array(z.string()),
  attackMotions: z.array(z.unknown()),
  battleBgm: AudioSchema,
  battleback1Name: z.string(),
  battleback2Name: z.string(),
  battlerHue: z.number(),
  battlerName: z.string(),
  battleSystem: z.number(),
  boat: z.unknown(),
  currencyUnit: z.string(),
  defeatMe: AudioSchema,
  editMapId: z.number(),
  elements: z.array(z.string()),
  equipTypes: z.array(z.string()),
  gameTitle: z.string(),
  gameoverMe: AudioSchema,
  locale: z.string(),
  magicSkills: z.array(z.number()),
  menuCommands: z.array(z.boolean()),
  optAutosave: z.boolean(),
  optDisplayTp: z.boolean(),
  optDrawTitle: z.boolean(),
  optExtraExp: z.boolean(),
  optFloorDeath: z.boolean(),
  optFollowers: z.boolean(),
  optKeyItemsNumber: z.boolean(),
  optSideView: z.boolean(),
  optSlipDeath: z.boolean(),
  optTransparent: z.boolean(),
  partyMembers: z.array(z.number()),
  ship: z.unknown(),
  skillTypes: z.array(z.string()),
  sounds: z.array(AudioSchema),
  startMapId: z.number(),
  startX: z.number(),
  startY: z.number(),
  switches: z.array(z.string()),
  terms: z.unknown(),
  testBattlers: z.array(z.unknown()),
  testTroopId: z.number(),
  title1Name: z.string(),
  title2Name: z.string(),
  titleBgm: AudioSchema,
  titleCommandWindow: z.unknown(),
  variables: z.array(z.string()),
  versionId: z.number(),
  victoryMe: AudioSchema,
  weaponTypes: z.array(z.string()),
  windowTone: z.array(z.number()),
}).passthrough();

export type System = z.infer<typeof SystemSchema>;
